agriculture/urls.py
from django.urls import path
from . import views

app_name = 'agriculture'
urlpatterns = [
    path('', views.agriculture_bot, name='agriculture'),
]

chatterpatter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('home.urls')),
    path('health',include('health.urls') ),
    path('agriculture',include('agriculture.urls') ),
    path('culture',include('culture.urls') ),
    path('economics',include('economics.urls') ),
    path('politics',include('politics.urls') )
]

culture/urls.py
from django.urls import path
from . import views

app_name = 'culture'
urlpatterns = [
    path('', views.culture_bot, name='culture'),
]

economics/urls.py
from django.urls import path
from . import views

app_name = 'economics'
urlpatterns = [
    path('', views.economics_bot, name='economics'),
]

health/urls.py
from django.urls import path
from . import views

app_name = 'health'
urlpatterns = [
    path('', views.health_bot, name='health'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

politics/urls.py
from django.urls import path
from . import views

app_name = 'politics'
urlpatterns = [
    path('', views.politics_bot, name='politics'),
]

agriculture/models.py
from django.db import models

# Create your models here.

culture/models.py
from django.db import models

# Create your models here.

economics/models.py
from django.db import models

# Create your models here.

health/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

politics/models.py
from django.db import models

# Create your models here.

agriculture/views.py
from django.shortcuts import render
from . import agriculture

def agriculture_bot(request):
    if request.session.get('ques') is None:
        request.session['ques'] = []
        request.session['ans'] = []
        ques= []
        ans= []
    if request.method == "POST":
        if request.POST['button'] == 'Clear History':
            request.session['ques'] = []
            request.session['ans'] = []
            ques= []
            ans= []
        else:
            user_ques = request.POST.get('ques')
            bot_ans = agriculture.chatbot_response(user_ques)
            ques = request.session['ques']
            ques.append(user_ques)
            request.session['ques'] = ques
            ans = request.session['ans']
            ans.append(bot_ans)
            request.session['ans'] = ans
    fuse = zip(request.session['ques'], request.session['ans'])
    return render(request, 'agriculture/index.html', {'fuse': fuse})

culture/views.py
from django.shortcuts import render
from . import culture

def culture_bot(request):
    if request.session.get('ques1') is None:
        request.session['ques1'] = []
        request.session['ans1'] = []
        ques=[]
        ans=[]
    if request.method == "POST":
        if request.POST['button'] == 'Clear History':
            request.session['ques1'] = []
            request.session['ans1'] = []
            ques= []
            ans= []
        else:
            user_ques = request.POST.get('ques')
            bot_ans = culture.chatbot_response(user_ques)
            ques = request.session['ques1']
            ques.append(user_ques)
            request.session['ques1'] = ques
            ans = request.session['ans1']
            ans.append(bot_ans)
            request.session['ans1'] = ans
    fuse = zip(request.session['ques1'], request.session['ans1'])
    return render(request, 'culture/index.html', {'fuse': fuse})

economics/views.py
from django.shortcuts import render
from . import economics

def economics_bot(request):
    if request.session.get('ques2') is None:
        request.session['ques2'] = []
        request.session['ans2'] = []
        ques=[]
        ans=[]
    if request.method == "POST":
        if request.POST['button'] == 'Clear History':
            request.session['ques2'] = []
            request.session['ans2'] = []
            ques= []
            ans= []
        else:
            user_ques = request.POST.get('ques')
            bot_ans = economics.chatbot_response(user_ques)
            ques = request.session['ques2']
            ques.append(user_ques)
            request.session['ques2'] = ques
            ans = request.session['ans2']
            ans.append(bot_ans)
            request.session['ans2'] = ans
    fuse = zip(request.session['ques2'], request.session['ans2'])
    return render(request, 'economics/index.html', {'fuse': fuse})

health/views.py
from django.shortcuts import render
from . import health

def health_bot(request):
    if request.session.get('ques3') is None:
        request.session['ques3'] = []
        request.session['ans3'] = []
        ques=[]
        ans=[]
    if request.method == "POST":
        if request.POST['button'] == 'Clear History':
            request.session['ques3'] = []
            request.session['ans3'] = []
            ques= []
            ans= []
        else:
            user_ques = request.POST.get('ques')
            bot_ans = health.chatbot_response(user_ques)
            ques = request.session['ques3']
            ques.append(user_ques)
            request.session['ques3'] = ques
            ans = request.session['ans3']
            ans.append(bot_ans)
            request.session['ans3'] = ans    
    fuse = zip(request.session['ques3'], request.session['ans3'])
    return render(request, 'health/index.html', {'fuse': fuse})

home/views.py
from django.shortcuts import render
import requests


def home(request):
    res = requests.get("https://nepalcorona.info/api/v1/data/nepal")
    data = res.json()
    return render(request, 'home/index.html', {"positive": data["tested_positive"], "recovered": data["recovered"], "deaths": data["deaths"]})

politics/views.py
from django.shortcuts import render
from . import politics

def politics_bot(request):
    if request.session.get('ques4') is None:
        request.session['ques4'] = []
        request.session['ans4'] = []
        ques=[]
        ans=[]
    if request.method == "POST":
        if request.POST['button'] == 'Clear History':
            request.session['ques4'] = []
            request.session['ans4'] = []
            ques= []
            ans= []
        else:
            user_ques = request.POST.get('ques')
            bot_ans = politics.chatbot_response(user_ques)
            ques = request.session['ques4']
            ques.append(user_ques)
            request.session['ques4'] = ques
            ans = request.session['ans4']
            ans.append(bot_ans)
            request.session['ans4'] = ans    
    fuse = zip(request.session['ques4'], request.session['ans4'])
    return render(request, 'politics/index.html', {'fuse': fuse})

agriculture/templates/agriculture/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Chatbot | Agriculture</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style media="screen">
    .button{
      border-radius: 4px;
      padding: 10px 24px;
      background-color: #87CEEB;}
    .button:hover {background-color: #008B8B;
    }
    .qabox{
      background-color:#E0FFFF;
      color: #00008B;
      border-radius: 5px;
    }
    body{
      background-color:#ADD8E6;
      font-family: "Montserrat", sans-serif;
    }
    h1{
      font-family: "Times New Roman", Times, serif, Helvetica;
      color: #00008B;
    }
  </style>
</head>

<body>
  <h1 class='text-center mt-3'>Agriculture Chatbot</h1>

  <div class="row text-left mt-4">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8 qabox p-3">
      <a href="#bottom" class="float-right">Go to Bottom</a>
      {% for ques, ans in fuse %}

      <p>Q: {{ques}}</p>

      <p>A: {{ans|safe}}</p>
      {% endfor %}
      <hr>
      <form action="{% url 'agriculture:agriculture' %}" method="post">
        {% csrf_token %}
        <textarea name="ques" class='rounded bg-light' placeholder="Enter your query" rows="3" cols="50" style='width:100%'></textarea>
<a href="{% url 'home:home' %}">Go Back</a> <input type="submit" id="bottom" name='button' value='Submit' class="button float-right">
      </form>
    </div>
    <div class="col-lg-2">
      <form action="{% url 'agriculture:agriculture' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clear History" name='button' class="button float-left">
      </form>
    </div>
  </div>
</body>

</html>

culture/templates/culture/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Chatbot | Culture</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style media="screen">
    .button{
      border-radius: 4px;
      padding: 10px 24px;
      background-color: #87CEEB;}
    .button:hover {background-color: #008B8B;
    }
    .qabox{
      background-color:#E0FFFF;
      color: #00008B;
      border-radius: 5px;
    }
    body{
      background-color:#ADD8E6;
      font-family: "Montserrat", sans-serif;
    }
    h1{
      font-family: "Times New Roman", Times, serif, Helvetica;
      color: #00008B;
    }
  </style>
</head>

<body>
  <h1 class='text-center mt-3'>Culture Chatbot</h1>

  <div class="row text-left mt-4">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8 qabox p-3">
      <a href="#bottom" class="float-right">Go to Bottom</a>
      {% for ques, ans in fuse %}

      <p>Q: {{ques}}</p>

      <p>A: {{ans|safe}}</p>
      {% endfor %}
      <hr>
      <form action="{% url 'culture:culture' %}" method="post">
        {% csrf_token %}
        <textarea name="ques" class='rounded bg-light' placeholder="Enter your query" rows="3" cols="50" style='width:100%'></textarea>
<a href="{% url 'home:home' %}">Go Back</a> <input type="submit" id="bottom" name='button' value='Submit' class="button float-right">
      </form>
    </div>
    <div class="col-lg-2">
      <form action="{% url 'culture:culture' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clear History" name='button' class="button float-left">
      </form>
    </div>
  </div>
</body>

</html>

economics/templates/economics/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Chatbot | Economics</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style media="screen">
    .button{
      border-radius: 4px;
      padding: 10px 24px;
      background-color: #87CEEB;}
    .button:hover {background-color: #008B8B;
    }
    .qabox{
      background-color:#E0FFFF;
      color: #00008B;
      border-radius: 5px;
    }
    body{
      background-color:#ADD8E6;
      font-family: "Montserrat", sans-serif;
    }
    h1{
      font-family: "Times New Roman", Times, serif, Helvetica;
      color: #00008B;
    }
  </style>
</head>

<body>
  <h1 class='text-center mt-3'>Economics Chatbot</h1>

  <div class="row text-left mt-4">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8 qabox p-3">
      <a href="#bottom" class="float-right">Go to Bottom</a>
      {% for ques, ans in fuse %}

      <p>Q: {{ques}}</p>

      <p>A: {{ans|safe}}</p>
      {% endfor %}
      <hr>
      <form action="{% url 'economics:economics' %}" method="post">
        {% csrf_token %}
        <textarea name="ques" class='rounded bg-light' placeholder="Enter your query" rows="3" cols="50" style='width:100%'></textarea>
<a href="{% url 'home:home' %}">Go Back</a> <input type="submit" id="bottom" name='button' value='Submit' class="button float-right">
      </form>
    </div>
    <div class="col-lg-2">
      <form action="{% url 'economics:economics' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clear History" name='button' class="button float-left">
      </form>
    </div>
  </div>
</body>

</html>

health/templates/health/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Chatbot | Health</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style media="screen">
    .button{
      border-radius: 4px;
      padding: 10px 24px;
      background-color: #87CEEB;}
    .button:hover {background-color: #008B8B;
    }
    .qabox{
      background-color:#E0FFFF;
      color: #00008B;
      border-radius: 5px;
    }
    body{
      background-color:#ADD8E6;
      font-family: "Montserrat", sans-serif;
    }
    h1{
      font-family: "Times New Roman", Times, serif, Helvetica;
      color: #00008B;
    }
  </style>
</head>

<body>
  <h1 class='text-center mt-3'>Health Chatbot</h1>

  <div class="row text-left mt-4">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8 qabox p-3">
      <a href="#bottom" class="float-right">Go to Bottom</a>
      {% for ques, ans in fuse %}

      <p>Q: {{ques}}</p>

      <p>A: {{ans|safe}}</p>
      {% endfor %}
      <hr>
      <form action="{% url 'health:health' %}" method="post">
        {% csrf_token %}
        <textarea name="ques" class='rounded bg-light' placeholder="Enter your query" rows="3" cols="50" style='width:100%'></textarea>
<a href="{% url 'home:home' %}">Go Back</a> <input type="submit" id="bottom" name='button' value='Submit' class="button float-right">
      </form>
    </div>
    <div class="col-lg-2">
      <form action="{% url 'health:health' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clear History" name='button' class="button float-left">
      </form>
    </div>
  </div>
</body>

</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Chatbot</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style media="screen">
    @media (min-width: 990px) {
      .box {
        width: 100%;
        margin: auto;
      }
    }
    @media (max-width: 989px) {
      .box {
        width: 50%;
        margin: auto;
      }
    }
    .image:hover {
      opacity: 0.3;
    }
    body {
      background-color: #ADD8E6;
      font-family: "Montserrat", sans-serif;
    }
    h1{
      color:blue;
      font-family: "Times New Roman", Times, serif, Helvetica;
    }
    footer {
      background-color: #66CDAA;
    }
  </style>
</head>

<body>
  <h1 class='text-center p-1 mb-5 mt-3'>CHATTER-PATTER</h1>
  <div class="row mb-4 ml-5 mr-1">
    <div class="col-lg-3 text-center">
      <a href="{% url 'agriculture:agriculture' %}"><img src='https://www.openaccessgovernment.org/wp-content/uploads/2018/09/dreamstime_s_99609915.jpg' class="rounded image mx-auto d-block" width='300' height="300"></a>
      <div class="box text-center mt-2">
        <h2>Agriculture</h2>
        <p>This bot talks about the various agriculture related topics </p>
      </div>
    </div>
    <div class="col-lg-1">
    </div>
    <div class="col-lg-3 text-center">
      <a href="{% url 'health:health' %}"><img src='https://fontmeme.com/images/womens-health-mag.png' class="rounded image mx-auto d-block" width='300' height="300"></a>
      <div class="box text-center mt-2">
        <h2>Health</h2>
        <p>This bot generally talks on woman health and gives you brief idea of what to eat and health tips during mensturation </p>
      </div>
    </div>
    <div class="col-lg-1">
    </div>
    <div class="col-lg-3 text-center">
      <a href="{% url 'politics:politics' %}"><img src='https://www.imf.org/external/pubs/ft/fandd/2020/06/images/frieden-1600.jpg' class="rounded image mx-auto d-block" width='300' height="300"></a>
      <div class="box text-center mt-2">
        <h2>Politics</h2>
        <p>This bot talks about the political condition of Nepal </p>
      </div>
    </div>
    <div class="col-lg-1">
    </div>
  </div>
  <div class="row m-3 p-1">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-3 text-center">
      <a href="{% url 'economics:economics' %}"><img src='https://www.nationalbusinessmirror.com/wp-content/uploads/2020/07/economic-situation.jpg' class="rounded image mx-auto d-block" width='300' height="300"></a>
      <div class="box text-center mt-2">
        <h2>Economics</h2>
        <p>This bot talks about the economics condition of Nepal </p>
      </div>
    </div>
    <div class="col-lg-1">
    </div>
    <div class="col-lg-3">
      <a href="{% url 'culture:culture' %}"><img src='https://i.pinimg.com/originals/59/c3/f1/59c3f179fa50d6439ecb6593f8f1d1b0.jpg' class="rounded image mx-auto d-block" width='300' height="300"></a>
      <div class="box text-center mt-2">
        <h2>Culture</h2>
        <p>This bot gives you the knowledge of cultural and environment theme of Nepal </p>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </div>

</body>

<footer>
<div class="row mt-4 p-3">

  <div class="col-lg-1">

  </div>
  <div class="col-lg-4 text-center">
    <h3>Nepal Covid-19 Update:</h3>
      <p>Total Positive Cases: {{positive}}</p>
      <p>Total Recovered: {{recovered}}</p>
      <p>Total Deaths: {{deaths}}</p>
  </div>
  <div class="col-lg-2">

  </div>
  <div class="col-lg-4 text-center">
        <h3>Contact us:</h3>
        <p>pantaayushma77@gmail.com</p>
        <p>dahalshrijak@gmail.com</p>
        <p>I.O.E. Thapathali Campus</p>
  </div>
  <div class="col-lg-1">

  </div>
</div>
<div class="row mb-2">
  <div class="col-lg text-center">
    <p>© 074BEX001/041</p>
  </div>

</div>
</footer>

</html>

politics/templates/politics/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Chatbot | Politics</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <style media="screen">
    .button{
      border-radius: 4px;
      padding: 10px 24px;
      background-color: #87CEEB;}
    .button:hover {background-color: #008B8B;
    }
    .qabox{
      background-color:#E0FFFF;
      color: #00008B;
      border-radius: 5px;
    }
    body{
      background-color:#ADD8E6;
      font-family: "Montserrat", sans-serif;
    }
    h1{
      font-family: "Times New Roman", Times, serif, Helvetica;
      color: #00008B;
    }
  </style>
</head>

<body>
  <h1 class='text-center mt-3'>Politics Chatbot</h1>

  <div class="row text-left mt-4">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8 qabox p-3">
      <a href="#bottom" class="float-right">Go to Bottom</a>
      {% for ques, ans in fuse %}

      <p>Q: {{ques}}</p>

      <p>A: {{ans|safe}}</p>
      {% endfor %}
      <hr>
      <form action="{% url 'politics:politics' %}" method="post">
        {% csrf_token %}
        <textarea name="ques" class='rounded bg-light' placeholder="Enter your query" rows="3" cols="50" style='width:100%'></textarea>
<a href="{% url 'home:home' %}">Go Back</a> <input type="submit" id="bottom" name='button' value='Submit' class="button float-right">
      </form>
    </div>
    <div class="col-lg-2">
      <form action="{% url 'politics:politics' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clear History" name='button' class="button float-left">
      </form>
    </div>
  </div>
</body>

</html>